import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type { Annotation, AnnotationFile, AnnotationInput } from './types';

const DIR = '.semantic-inspector';

/** Absolute paths for the annotation files, derived only from rootDir. */
export function annotationPaths(rootDir: string): { dir: string; json: string; md: string } {
  const dir = resolve(rootDir, DIR);
  return { dir, json: join(dir, 'annotations.json'), md: join(dir, 'annotations.md') };
}

/** Read annotations.json, or an empty file if it does not exist. Throws on malformed JSON. */
export function readAnnotations(rootDir: string): AnnotationFile {
  const { json } = annotationPaths(rootDir);
  if (!existsSync(json)) return { version: 1, annotations: {} };
  return JSON.parse(readFileSync(json, 'utf8')) as AnnotationFile;
}

/** Insert or replace an annotation by name. createdAt is preserved across updates; now is injected. */
export function upsert(file: AnnotationFile, input: AnnotationInput, now: string): AnnotationFile {
  const prev = file.annotations[input.name];
  const next: Annotation = {
    name: input.name,
    tags: input.tags,
    note: input.note,
    anchor: input.anchor,
    lastSeen: input.lastSeen,
    createdAt: prev?.createdAt ?? now,
    updatedAt: now
  };
  return { version: 1, annotations: { ...file.annotations, [input.name]: next } };
}

// Keep interpolated values on one line so a stray newline can't forge a new "## " section in the mirror.
function inline(s: string): string {
  return s.replace(/\s*\r?\n\s*/g, ' ');
}

/** Render the human/Graphify-readable Markdown mirror. Pure. */
export function renderMarkdown(file: AnnotationFile): string {
  const lines: string[] = [
    '# Semantic annotations',
    '',
    '> Generated by semantic-inspector. Source of truth: annotations.json. Do not edit by hand.',
    ''
  ];
  for (const name of Object.keys(file.annotations).sort()) {
    const a = file.annotations[name];
    lines.push(`## ${inline(name)}`, '');
    if (a.tags?.length) lines.push(`- **tags:** ${a.tags.map(inline).join(', ')}`);
    const pathStr = a.anchor.path?.length ? ` (${a.anchor.path.map(inline).join(' › ')})` : '';
    lines.push(`- **component:** ${inline(a.anchor.comp)}${pathStr}`);
    if (a.anchor.text) lines.push(`- **text:** "${inline(a.anchor.text)}"`);
    if (a.anchor.index != null && a.anchor.total != null) {
      lines.push(`- **index:** ${a.anchor.index}/${a.anchor.total}`);
    }
    if (a.anchor.attrs) {
      for (const [k, v] of Object.entries(a.anchor.attrs)) {
        lines.push(`- **${k === 'data-testid' ? 'testid' : k}:** ${v}`);
      }
    }
    if (a.lastSeen.loc) lines.push(`- **last seen:** ${inline(a.lastSeen.loc)} _(hint — may be stale, verify)_`);
    if (a.note) lines.push(`- **note:** ${inline(a.note)}`);
    lines.push('');
  }
  return lines.join('\n');
}

/** Write annotations.json (source of truth) then regenerate the Markdown mirror (best-effort). */
export function writeAnnotations(rootDir: string, file: AnnotationFile): void {
  const { dir, json, md } = annotationPaths(rootDir);
  mkdirSync(dir, { recursive: true });
  writeFileSync(json, `${JSON.stringify(file, null, 2)}\n`, 'utf8');
  try {
    writeFileSync(md, renderMarkdown(file), 'utf8');
  } catch {
    // Mirror is derived/best-effort; annotations.json is the source of truth and already written.
  }
}
